# Generated by Django 5.0.6 on 2024-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id_question",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("text", models.CharField(max_length=4096)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
