# Generated by Django 5.0.6 on 2024-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
