# Generated by Django 5.0.6 on 2024-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_answer_id_answer_alter_question_id_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="source",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
