# Generated by Django 5.0.6 on 2024-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_answer_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="source",
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
