# Generated by Django 5.0.6 on 2024-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0009_historicalanswer"),
        ("tags", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(related_name="questions", to="tags.tag"),
        ),
    ]
