# Generated by Django 5.0.6 on 2024-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0010_question_tags"),
        ("tags", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="tags.tag"
            ),
        ),
    ]
