# Generated by Django 5.0.6 on 2024-06-04 13:22

import tags.colors
import tags.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.SlugField(max_length=64)),
                (
                    "color",
                    tags.fields.ColorField(
                        default=tags.colors.Color.random_color,
                        help_text="Label color in hex mode",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
