# Generated by Django 5.0.6 on 2024-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
