# Generated by Django 5.0.6 on 2024-06-09 14:25

from django.db import migrations


def set_tag_description(apps, schema_editor):
    Tag = apps.get_model("tags", "Tag")
    for tag in Tag.objects.filter(description=''):
        tag.description = tag.name.capitalize()
        tag.save()


def clear_tag_description(apps, schema_editor):
    Tag = apps.get_model("tags", "Tag")
    for tag in Tag.objects.exclude(description=None):
        tag.description = ''
        tag.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_tag_description"),
        ]

    operations = [
        migrations.RunPython(set_tag_description, clear_tag_description),
        ]
