# Generated by Django 5.0.6 on 2024-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0004_default_description_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.CharField(
                default="",
                help_text="Textual description of label",
                max_length=255,
                unique=True,
            ),
        ),
    ]
